#!/usr/bin/env python3
"""threadlight-deploy ``generate_only: true``: a deploy-ready repo with no subscription.

Turns a Threadlight design workspace (``specs/SPEC.md``, ``specs/manifest.json``,
``specs/sample-data/``, ``AGENTS.md``, ``src/agent/skills/``) into a complete
repository that the user deploys later with their own credentials
(``azd auth login`` + ``azd up``). It runs deploy Phases 0/1/2/3/5/6 from the
vendored GHCP pilot scaffold only:

* no ``azd ai agent init`` (it needs a login and writes nothing without one),
* no az/azd/docker invocation, no network, no Azure resources;
* the ONLY canonical sources are ``references/hosted-agent/ghcp/references``
  (agent runtime) and its ``pilot/`` (azure.yaml with the INLINE hosted agent
  definition, hooks, infra/main.bicep, mock MCP server) plus
  ``references/generate-only`` (eval lock, runner template).

Every Threadlight agent runs in Microsoft Foundry. The generated agent is a
Foundry HOSTED agent; ``agent_type: prompt`` in SPEC section 11e is refused
here (exit 4) because the GHCP pilot scaffold is hosted-only.

Usage::

    python generate_only.py --project <workspace> [--force]

Exit codes: 0 generated, 2 invalid workspace, 4 prompt agent requested,
5 would overwrite generated files (re-run with ``--force``).
"""
from __future__ import annotations

import argparse
import json
import pprint
import re
import shutil
import sys
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
DEPLOY = HERE.parent
GHCP = DEPLOY / "references" / "hosted-agent" / "ghcp" / "references"
PILOT = GHCP / "pilot"
GEN = DEPLOY / "references" / "generate-only"

MARKER = "generated by threadlight-deploy generate-only"
BUILTIN_EVALUATORS = ("builtin.task_adherence", "builtin.intent_resolution", "builtin.coherence")
RUBRIC_THRESHOLD = 4
READ_PREFIXES = ("get_", "list_", "query_", "search_", "find_", "lookup_", "fetch_", "check_", "read_")
MANY_PREFIXES = ("list_", "query_", "search_", "find_")

DEMO_SANDBOX_POSTURE = {
    "networking": "public",
    "replicas": "single",
    "model_pinning": "preview-ok",
    "retention": "90d",
    "defender": "off (SecurityControl=Ignore tag)",
    "cost_alerts": "none",
    "dr": "none",
}


class PromptAgentRefused(Exception):
    """SPEC asks for a prompt agent; generate-only emits hosted agents only."""


class OverwriteRefused(Exception):
    """Generated files already exist and --force was not given."""

    def __init__(self, files: list[str]):
        super().__init__(", ".join(files))
        self.files = files


class WorkspaceError(Exception):
    pass


# --------------------------------------------------------------------------- SPEC parsing

def _slug(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug or "threadlight-agent"


def _section(spec: str, number: str) -> str:
    """Body of ``## <number>.`` up to the next level-2 heading."""
    m = re.search(rf"^##\s+{re.escape(number)}\b[^\n]*\n(.*?)(?=^##\s|\Z)", spec, re.M | re.S)
    return m.group(1) if m else ""


def _table_rows(block: str) -> list[list[str]]:
    rows = []
    for line in block.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            if rows:
                break
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if all(re.fullmatch(r":?-{2,}:?", c) for c in cells if c):
            continue
        rows.append(cells)
    return rows


def _tables(block: str) -> list[list[list[str]]]:
    tables, current = [], []
    for line in block.splitlines() + [""]:
        if line.strip().startswith("|"):
            current.append(line)
        elif current:
            tables.append(_table_rows("\n".join(current)))
            current = []
    return [t for t in tables if t]


def _strip_ticks(text: str) -> str:
    return text.replace("`", "").strip()


def agent_type(spec: str) -> str:
    m = re.search(r"^\s*agent_type:\s*([A-Za-z_-]+)", spec, re.M)
    return m.group(1).lower() if m else "hosted"


def business_rules(spec: str) -> dict[str, str]:
    rules: dict[str, str] = {}
    for m in re.finditer(r"^#{2,4}\s*(BR-\d+)\s*[:\-—]\s*(.+)$", spec, re.M):
        rules.setdefault(m.group(1), m.group(2).strip())
    for m in re.finditer(r"\|\s*\*{0,2}`?(BR-\d+)`?\*{0,2}\s*\|\s*([^|]+)\|", spec):
        rules.setdefault(m.group(1), _strip_ticks(m.group(2)).strip("* "))
    return dict(sorted(rules.items(), key=lambda kv: int(kv[0].split("-")[1])))


def _expand_rule_ids(text: str) -> list[str]:
    ids: list[str] = []
    for m in re.finditer(r"BR-(\d+)((?:\s*[,/]\s*\d+)*)", text):
        width = len(m.group(1))
        for num in [m.group(1)] + re.findall(r"\d+", m.group(2)):
            rid = f"BR-{int(num):0{width}d}"
            if rid not in ids:
                ids.append(rid)
    return ids


def _identifier(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", name).strip("_")
    if not ident or ident[0].isdigit():
        ident = f"t_{ident}"
    return ident


VALUE_WORDS = {
    "amount", "value", "price", "total", "reason", "text", "sku", "score", "method", "status",
    "history", "context", "notes", "note", "query", "decision", "rationale", "category",
    "quantity", "date", "type", "message", "description", "photo", "photos", "uri", "uris",
}


PLACEHOLDER_INPUTS = re.compile(
    r"^\s*(?:none|n/?a|nil|-|—|–|tbd|see\s+below|none\s*/\s*see\s+below|see\s+section\s+6\w*)\s*\.?\s*$", re.I)
EXPLICIT_NO_INPUTS = re.compile(r"^\s*(?:none|n/?a|nil|-|—|–)\s*\.?\s*$", re.I)
PLACEHOLDER_WORDS = {"none", "see", "below", "above", "n", "a", "na", "tbd", "nil"}
TYPE_MAP = {
    "string": "str", "str": "str", "text": "str", "datetime": "str", "date": "str", "time": "str",
    "uuid": "str", "id": "str", "enum": "str", "boolean": "bool", "bool": "bool",
    "integer": "int", "int": "int", "number": "float", "float": "float", "decimal": "float",
}


def _is_placeholder(text: str) -> bool:
    return not _strip_ticks(text).strip() or bool(PLACEHOLDER_INPUTS.match(_strip_ticks(text)))


def _arg_type(raw: str) -> str:
    raw = raw.strip().strip("`").lower()
    if raw.endswith("[]") or raw.startswith(("array", "list")):
        return "list[str]"
    return TYPE_MAP.get(re.split(r"[\s(|<]", raw)[0] if raw else "", "str")


def _prose_args(inputs: str) -> list[dict[str, Any]]:
    """Free-text SPEC inputs ('case + order + amount') -> optional str args."""
    args: list[dict[str, Any]] = []
    if _is_placeholder(inputs):
        return args
    text = re.sub(r"\([^)]*\)", "", inputs.lower())
    for token in re.split(r"\s*(?:\+|,|;|/|\band\b)\s*", text):
        words = re.findall(r"[a-z][a-z0-9]*", token)
        if not words or len(words) > 3 or set(words) <= PLACEHOLDER_WORDS:
            continue
        if len(words) == 1 and words[0] not in VALUE_WORDS and not words[0].endswith("id"):
            name = f"{words[0]}_id"
        else:
            name = "_".join(words)
        name = _identifier(name)
        if name not in {a["name"] for a in args}:
            args.append({"name": name, "type": "str", "optional": True})
    return args


def _ticked_args(inputs: str) -> list[dict[str, Any]]:
    """Table-cell inputs: `a`, optional `b`, `ids[]`."""
    required, optional = [], []
    for m in re.finditer(r"(optional\s+)?`([A-Za-z_][A-Za-z0-9_]*)(\[\])?`", inputs, re.I):
        arg = {"name": _identifier(m.group(2)), "type": "list[str]" if m.group(3) else "str"}
        if any(a["name"] == arg["name"] for a in required + optional):
            continue
        (optional if m.group(1) else required).append(arg)
    for arg in optional:
        arg["optional"] = True
    return required + optional


def _subsection_args(body: str) -> list[dict[str, Any]] | None:
    """``- **Inputs**:`` as prose (`name: type` required) or a Parameter table. None when absent."""
    m = re.search(r"^\s*[-*]\s*\*\*(?:Inputs?|Parameters?|Arguments?)\*\*\s*:?(.*?)(?=^\s*[-*]\s*\*\*|^#{2,4}\s|\Z)",
                  body, re.M | re.S | re.I)
    if not m:
        return None
    text = m.group(1)
    args: list[dict[str, Any]] = []
    for table in _tables(text):
        header = [h.lower() for h in table[0]]
        i_name = next((i for i, h in enumerate(header) if h in {"parameter", "name", "input", "argument", "field"}), 0)
        i_type = next((i for i, h in enumerate(header) if "type" in h), None)
        i_req = next((i for i, h in enumerate(header) if "required" in h), None)
        for row in table[1:]:
            name = _identifier(_strip_ticks(row[i_name]).split()[0]) if i_name < len(row) and row[i_name].strip() else ""
            if not name or name in {a["name"] for a in args}:
                continue
            arg = {"name": name, "type": _arg_type(row[i_type]) if i_type is not None and i_type < len(row) else "str"}
            req = row[i_req].strip().lower() if i_req is not None and i_req < len(row) else "yes"
            if req in {"no", "n", "false", "optional"}:
                arg["optional"] = True
            args.append(arg)
    if args:
        return [a for a in args if not a.get("optional")] + [a for a in args if a.get("optional")]
    for line in [ln for ln in text.splitlines() if not ln.strip().startswith("|")]:
        for pm in re.finditer(r"`([A-Za-z_][A-Za-z0-9_]*)(\[\])?\s*(?::\s*([A-Za-z_][A-Za-z0-9_\[\]]*))?`([^`,;]*)", line):
            name = _identifier(pm.group(1))
            if name in {a["name"] for a in args}:
                continue
            arg = {"name": name, "type": "list[str]" if pm.group(2) else _arg_type(pm.group(3) or "str")}
            if not pm.group(3) and not re.search(r"\b(required|optional)\b", pm.group(4), re.I):
                continue  # a ticked example value such as `MEM-###`, not a parameter
            if re.search(r"\boptional\b", pm.group(4), re.I):
                arg["optional"] = True
            args.append(arg)
    if not args:
        return [] if _is_placeholder(text) else None
    return [a for a in args if not a.get("optional")] + [a for a in args if a.get("optional")]


def _tool_subsections(block: str) -> dict[str, dict[str, Any]]:
    """``### `tool_name` — BR-...`` subsections of section 6, in order."""
    found: dict[str, dict[str, Any]] = {}
    for m in re.finditer(r"^#{3,4}\s+(`?)([A-Za-z_][A-Za-z0-9_]*)\1(?=[\s:—–-]|$)[^\n]*\n(.*?)(?=^#{2,4}\s|\Z)",
                         block, re.M | re.S):
        body = m.group(3)
        # Unticked template headings (``### get_member``) count only with tool bullets.
        if not m.group(1) and not re.search(r"^\s*[-*]\s*\*\*(?:Inputs?|Parameters?|Arguments?|Description)\*\*",
                                            body, re.M | re.I):
            continue
        desc = re.search(r"^\s*[-*]\s*\*\*Description\*\*\s*:?\s*(.+)$", body, re.M | re.I)
        inputs = re.search(r"^\s*[-*]\s*\*\*(?:Inputs?|Parameters?|Arguments?)\*\*\s*:?(.*?)(?=^\s*[-*]\s*\*\*|^#{2,4}\s|\Z)",
                           body, re.M | re.S | re.I)
        found[_identifier(m.group(2))] = {
            "args": _subsection_args(body),
            "no_inputs": bool(inputs and EXPLICIT_NO_INPUTS.match(_strip_ticks(inputs.group(1)))),
            "description": _strip_ticks(desc.group(1)) if desc else "",
        }
    return found


def _consequences(spec: str) -> dict[str, str]:
    """Section 11a ``tools: - id: x / consequence: y`` and section 5b Read/Write column -> read|write."""
    kinds: dict[str, str] = {}
    sec5b = re.search(r"^#{2,3}\s*5b\b[^\n]*\n(.*?)(?=^##\s+(?!5b)\d|\Z)", spec, re.M | re.S | re.I)
    for table in _tables(sec5b.group(1) if sec5b else ""):
        header = [h.lower().replace(" ", "") for h in table[0]]
        i_rw = next((i for i, h in enumerate(header) if h in {"read/write", "r/w", "access", "mode"}), None)
        if i_rw is None or "tool" not in header[0]:
            continue
        for row in table[1:]:
            names = re.findall(r"`([A-Za-z_][A-Za-z0-9_]*)`", row[0]) or [row[0].strip()]
            mode = row[i_rw].strip().upper().replace(" ", "") if i_rw < len(row) else ""
            if names and mode:
                kinds[_identifier(names[0])] = "read" if mode in {"R", "READ", "READ-ONLY", "RO"} else "write"
    sec11a = re.search(r"^#{2,4}\s*11a\b[^\n]*\n(.*?)(?=^#{2,4}\s*11[b-z]\b|^##\s+\d|\Z)", spec, re.M | re.S | re.I)
    if sec11a:
        for item in re.split(r"^\s*-\s+(?=id:)", sec11a.group(1), flags=re.M)[1:]:
            ident = re.match(r"id:\s*[\"']?([A-Za-z_][A-Za-z0-9_]*)", item)
            cons = re.search(r"^\s*consequence:\s*[\"']?([A-Za-z_-]+)", item.split("\n- ", 1)[0], re.M)
            if ident and cons:
                kinds[_identifier(ident.group(1))] = "read" if cons.group(1).lower() in {"read", "read-only", "read_only"} else "write"
    return kinds


def tools(spec: str) -> list[dict[str, Any]]:
    """SPEC section 6 (Tool Contracts) as a typed tool plan, in SPEC order.

    Section 6 may be a summary table, ``### `tool` `` subsections, or both. Per-tool
    ``**Inputs**`` subsections are canonical; table placeholders such as
    ``none / see below`` never become arguments. Read/write classification uses
    section 11a ``consequence`` first, then the section 5b Read/Write column,
    then the section 6 idempotency column, then the tool-name heuristic.
    """
    block = _section(spec, "6") or _section(spec, "5b")
    subsections = _tool_subsections(_section(spec, "6"))
    consequences = _consequences(spec)
    rows: dict[str, dict[str, Any]] = {}
    for table in _tables(block):
        header = [h.lower() for h in table[0]]
        if not header or "tool" not in header[0]:
            continue
        idx_input = next((i for i, h in enumerate(header) if "input" in h), 1)
        idx_idem = next((i for i, h in enumerate(header) if "idempot" in h or "failure" in h), None)
        idx_desc = next((i for i, h in enumerate(header) if "output" in h or "description" in h), idx_input + 1)
        for row in table[1:]:
            names = re.findall(r"`([A-Za-z_][A-Za-z0-9_]*)`", row[0]) or [row[0].strip()]
            name = _identifier(names[0])
            if not name or name in rows:
                continue
            inputs = row[idx_input] if idx_input < len(row) else ""
            rows[name] = {
                "args": [] if _is_placeholder(inputs) else (_ticked_args(inputs) or _prose_args(inputs)),
                "no_inputs": bool(EXPLICIT_NO_INPUTS.match(_strip_ticks(inputs))),
                "idem": row[idx_idem].lower() if idx_idem is not None and idx_idem < len(row) else "",
                "description": _strip_ticks(row[idx_desc]) if idx_desc < len(row) else "",
            }
    plan: list[dict[str, Any]] = []
    for name in list(rows) + [n for n in subsections if n not in rows]:
        row = rows.get(name, {"args": [], "no_inputs": False, "idem": "", "description": ""})
        sub = subsections.get(name, {})
        source = sub if sub.get("args") is not None else row
        args, no_inputs = source["args"], source.get("no_inputs", False) and not source["args"]
        idem = row["idem"]
        if name in consequences:
            kind = consequences[name]
        elif "read-only" in idem or "read only" in idem:
            kind = "read"
        else:
            kind = "read" if not idem and name.startswith(READ_PREFIXES) else "write"
        verb, _, noun = name.partition("_")
        nouns = [n for n in (noun or verb).split("_") if n]
        plan.append({
            "name": name,
            "kind": kind,
            "many": kind == "read" and name.startswith(MANY_PREFIXES),
            "nouns": nouns,
            "args": args,
            "description": sub.get("description") or row["description"],
            **({"no_inputs": True} if no_inputs else {}),
        })
    if not plan:
        raise WorkspaceError("SPEC section 6 (Tool Contracts) has no tool table or `### `tool`` subsections")
    return plan


def scenarios(spec: str) -> list[dict[str, Any]]:
    """SPEC section 9 evaluation scenarios table."""
    m = re.search(r"^#{2,4}\s*Evaluation\s+scenarios[^\n]*\n(.*?)(?=^#{2,4}\s|\Z)", spec, re.M | re.S | re.I)
    block = m.group(1) if m else _section(spec, "9")
    rows: list[dict[str, Any]] = []
    for table in _tables(block):
        header = [h.lower() for h in table[0]]
        if not header or header[0] != "id":
            continue

        def col(*keys: str) -> int | None:
            return next((i for i, h in enumerate(header) if any(k in h for k in keys)), None)

        i_scn, i_in, i_exp = col("scenario"), col("input"), col("expected")
        i_br, i_cat = col("business rule", "brs", "rules"), col("category")
        for row in table[1:]:
            get = lambda i: row[i] if i is not None and i < len(row) else ""  # noqa: E731
            sid = _strip_ticks(row[0])
            if not sid:
                continue
            query = _strip_ticks(get(i_in)) or _strip_ticks(get(i_scn))
            rows.append({
                "id": sid,
                "query": query,
                "expected": _strip_ticks(get(i_exp)),
                "business_rules": _expand_rule_ids(get(i_br)),
                "category": _strip_ticks(get(i_cat)) or "functional",
                "scenario": _strip_ticks(get(i_scn)),
            })
    if not rows:
        raise WorkspaceError("SPEC section 9 has no 'Evaluation scenarios' table")
    return rows


def design_dataset(project_dir: Path) -> list[dict[str, Any]]:
    """Reuse threadlight-design's validated tests/eval_dataset.jsonl verbatim when present."""
    path = project_dir / "tests" / "eval_dataset.jsonl"
    if not path.is_file():
        return []
    rows: list[dict[str, Any]] = []
    for n, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            raise WorkspaceError(f"tests/eval_dataset.jsonl line {n}: {exc}") from exc
        query = row.get("query") or row.get("prompt") or row.get("input")
        if not isinstance(row, dict) or not row.get("id") or not query:
            raise WorkspaceError(f"tests/eval_dataset.jsonl line {n}: needs 'id' and 'query' (or 'prompt')")
        rules = row.get("business_rules") or []
        rows.append({
            "id": str(row["id"]),
            "query": str(query),
            "expected": str(row.get("expected", "")),
            "business_rules": [str(r) for r in rules] if isinstance(rules, list) else _expand_rule_ids(str(rules)),
            "category": str(row.get("category") or "functional"),
            "scenario": str(row.get("scenario", "")),
        })
    return rows


# --------------------------------------------------------------------------- rendering

def _py_type(arg: dict[str, Any]) -> str:
    base = arg["type"]
    return f"Optional[{base}] = None" if arg.get("optional") else base


def render_mcp_server(project: str, plan: list[dict[str, Any]]) -> str:
    table = {t["name"]: {"kind": t["kind"], "many": t["many"], "nouns": t["nouns"]} for t in plan}
    funcs = []
    for t in plan:
        sig = ", ".join(f"{a['name']}: {_py_type(a)}" for a in t["args"])
        call = ", ".join(f'"{a["name"]}": {a["name"]}' for a in t["args"])
        doc = (t["description"] or f"{t['kind']} tool from SPEC section 6").replace('"""', "'")
        helper = "_read" if t["kind"] == "read" else "_write"
        funcs.append(
            f"@mcp.tool()\ndef {t['name']}({sig}) -> dict:\n"
            f'    """{doc}"""\n'
            f'    return {helper}("{t["name"]}", {{{call}}})\n'
        )
    text = (GEN / "templates" / "mcp_server.py.tmpl").read_text(encoding="utf-8")
    return (
        text.replace("{{PROJECT_NAME}}", project)
        .replace("{{TOOLS_TABLE}}", pprint.pformat(table, indent=4, sort_dicts=False))
        .replace("{{TOOL_FUNCTIONS}}", "\n\n".join(funcs))
    )


def render_azure_yaml(project: str, agent: str, description: str) -> str:
    text = (PILOT / "azure.yaml").read_text(encoding="utf-8")
    body = text[text.index("name: __PROJECT_NAME__"):]
    header = (
        "# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json\n"
        f"#\n# {MARKER} from the canonical Threadlight pilot azure.yaml.\n"
        "# The hosted agent is defined INLINE below (no agent.yaml). Keep\n"
        "# `remoteBuild: true`: images build in ACR, no local Docker login needed.\n"
    )
    desc = json.dumps(description or f"{agent} Foundry hosted agent")
    return header + (
        body.replace("__PROJECT_NAME__", project)
        .replace("__AGENT_NAME__", agent)
        .replace("__AGENT_DESCRIPTION__", desc)
    )


def render_posture(project: str) -> str:
    rows = "\n".join(f"  {k}: {v}" for k, v in DEMO_SANDBOX_POSTURE.items())
    return f"""# Deployment posture — {project}

<!-- {MARKER} -->

Generate-only run: nobody answered the T-0 deployment-target question, so the
posture is defaulted to the least-commitment target. Re-run T-0 before a real
deploy if the target is not a disposable demo sandbox.

```yaml
deployment_target: demo-sandbox
source: defaulted-after-skip
decided_at: generate-only
posture:
{rows}
```

| Control | demo-sandbox value |
|---|---|
""" + "\n".join(f"| {k} | {v} |" for k, v in DEMO_SANDBOX_POSTURE.items()) + "\n"


def render_deferred(project: str) -> str:
    return f"""# Deferred deploy steps — {project}

<!-- {MARKER} -->

This repository was produced by `threadlight-deploy` with `generate_only: true`:
no subscription, no az/azd login and no network. Phases 0, 1, 2, 3, 5 and 6
(offline parts) ran from the vendored pilot scaffold. The steps below need a
signed-in user and a subscription, so they are **deferred** to the person who
deploys this repo with their own credentials.

| Step | Status | What to do before/at deploy |
|---|---|---|
| T-0 deployment target | deferred | Confirm or replace the defaulted `demo-sandbox` posture in `specs/deployment-posture.md`. |
| Phase 3.5 live preflight (quota, region, RBAC, policy) | deferred | `azd auth login`, then check model quota and Foundry User/Owner rights in the target subscription. |
| Phase 6.5 Azure steps (deploy, smoke invoke, App Insights trace, Foundry eval run) | deferred | `azd up`, then `python evals/run_evals.py`; record agent id, trace id and eval run id in `specs/foundry-package-manifest.json`. |
| Phase 7 Citadel / gateway onboarding | deferred | Only if the posture requires Citadel; run `threadlight-citadel-spoke` after deploy. |
| Post-deploy tests (`tests/postdeploy-manifest.json`) | deferred | Phase stays `pending-deploy` until a real deploy refreshes it. |

Nothing here is evidence of a deployment. `skills/_shared/foundry_package.py`
reports this workspace as `INCOMPLETE` (exit 3) until the deferred evidence exists.
"""


def render_deploy_md(project: str, agent: str, plan: list[dict[str, Any]]) -> str:
    tool_list = ", ".join(f"`{t['name']}`" for t in plan)
    return f"""# Deploy {project}

<!-- {MARKER} -->

A Microsoft Foundry **hosted agent** (`{agent}`, GHCP runtime in `src/agent`)
plus a mock MCP tool server on Azure Container Apps (`src/mcp`, tools: {tool_list}).
The Container App hosts only the MCP tool server; the agent's reasoning and tool
loop run in Foundry. Generated offline with `generate_only: true`; see
`specs/deferred-steps.md` for what still needs your subscription.

## Prerequisites

- Azure Developer CLI with the `azure.ai.agents` extension, Azure CLI, Python 3.12.
- A subscription where you can create a resource group, a Foundry account and
  role assignments (Foundry User for the agent identity, granted by `hooks/postdeploy.sh`).
- Model quota for the deployment in `infra/main.bicep`.

## Offline checks (no login)

```sh
python -m pytest -q src/agent/tests
```

## Deploy with your own credentials

```sh
azd auth login
azd env new {project}
azd env set THREADLIGHT_OWNER "<your alias>"
azd env set THREADLIGHT_PURPOSE "pilot"
azd env set THREADLIGHT_DISPOSABLE "true"
azd up
```

Images build remotely in ACR (`remoteBuild: true`), so no local Docker daemon or
registry login is required.

## Evaluate after deploy (one command)

```sh
python -m pip install --require-hashes -r evals/requirements.lock
python evals/run_evals.py
```

`run_evals.py` reads `evals/eval-config.json` and `evals/eval_dataset.jsonl`,
runs built-in evaluators plus the SPEC-derived rubric against the hosted agent in
Foundry and records the eval run id in `specs/foundry-package-manifest.json`.
`python evals/run_evals.py --dry-run` prints the request offline.

## Delivery gate

```sh
python <threadlight-skills>/skills/_shared/foundry_package.py --workspace .
```

Exit 3 (`INCOMPLETE`) is expected until the agent id, trace id and a passing
eval run are recorded.
"""


def render_agent_tests(plan: list[dict[str, Any]], skills: list[str]) -> str:
    return f'''"""Offline unit tests for the generated hosted agent package ({MARKER}).

Static checks only: no network, no Azure login, no container.py import (it
needs the hosted-agent runtime packages).
"""
import ast
import json
import pprint
import re
from pathlib import Path

AGENT = Path(__file__).resolve().parents[1]
ROOT = AGENT.parents[1]
TOOLS = {json.dumps([t["name"] for t in plan])}
SKILLS = {json.dumps(skills)}


def _requirements(text):
    return [l for l in text.splitlines() if l and not l.startswith((" ", "#", "\\t"))]


def test_container_entrypoint_parses_and_serves_invocations():
    tree = ast.parse((AGENT / "container.py").read_text(encoding="utf-8"))
    names = {{n.name for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))}}
    assert "handle_invoke" in names


def test_instructions_and_skills_present():
    assert (AGENT / "copilot-instructions.md").read_text(encoding="utf-8").strip()
    for skill in SKILLS:
        text = (AGENT / "skills" / skill / "SKILL.md").read_text(encoding="utf-8")
        assert text.startswith("---"), skill


def test_agent_lock_is_exact_and_hashed():
    text = (AGENT / "requirements.lock").read_text(encoding="utf-8")
    reqs = _requirements(text)
    assert reqs and all("==" in r for r in reqs)
    assert text.count("--hash=sha256:") >= len(reqs)
    assert "--require-hashes" in (AGENT / "Dockerfile").read_text(encoding="utf-8")


def test_pyproject_dependencies_are_exact():
    text = (AGENT / "pyproject.toml").read_text(encoding="utf-8")
    deps = re.findall(r'^\\s*"([A-Za-z0-9_.\\-\\[\\]]+)\\s*([=<>~!]=?)', text, re.M)
    assert deps and all(op == "==" for _, op in deps)


def test_azure_yaml_declares_inline_hosted_agent():
    text = (ROOT / "azure.yaml").read_text(encoding="utf-8")
    assert "host: azure.ai.agent" in text and "kind: hosted" in text
    assert "__" not in text.split("name:", 1)[1]
    assert not (ROOT / "agent.yaml").exists() and not (AGENT / "agent.yaml").exists()


def test_mcp_server_exposes_spec_tools():
    tree = ast.parse((ROOT / "src" / "mcp" / "server.py").read_text(encoding="utf-8"))
    names = {{n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)}}
    assert set(TOOLS) <= names
'''


def build_eval_config(agent: str, rules: dict[str, str], scen: list[dict[str, Any]]) -> dict[str, Any]:
    rule_ids = sorted({r for s in scen for r in s["business_rules"]} | set(rules), key=lambda r: int(r.split("-")[1]))
    rule_text = "\n".join(f"- {rid}: {rules.get(rid, '(see SPEC section 3)')}" for rid in rule_ids)
    anchors = [
        "1: Wrong outcome or violates a business rule (e.g. auto-approves a case a rule sends to review).",
        "2: Outcome partly wrong or no business rule cited.",
        "3: Correct outcome but rationale incomplete or cites the wrong rule.",
        "4: Correct outcome, cites the rule(s) that fired, minor gaps.",
        "5: Correct outcome, cites every rule that fired, uses tool data, clear next step.",
    ]
    return {
        "schema": "threadlight-eval-config/v1",
        "generated_by": MARKER,
        "target": {"type": "azure_ai_agent", "name": agent},
        "input_messages": {"input": "{{item.query}}"},
        "dataset": "evals/eval_dataset.jsonl",
        "builtin_evaluators": [
            {
                "evaluator_name": name,
                "name": name.split(".", 1)[1],
                "data_mapping": {"query": "{{item.query}}", "response": "{{sample.output_text}}"},
            }
            for name in BUILTIN_EVALUATORS
        ],
        "custom_rubric_evaluators": [
            {
                "name": "spec_business_rules_rubric",
                "type": "score_model",
                "range": [1, 5],
                "threshold": RUBRIC_THRESHOLD,
                "anchors": anchors,
                "derived_from_acceptance_criteria": [s["id"] for s in scen] + rule_ids,
                "system_prompt": (
                    "You grade a business agent's answer against its SPEC. Business rules:\n"
                    f"{rule_text}\n\nScoring anchors:\n" + "\n".join(anchors)
                    + "\nReturn only the integer score."
                ),
                "user_prompt": (
                    "Request: {{item.query}}\nExpected outcome: {{item.expected}}\n"
                    "Agent answer: {{sample.output_text}}"
                ),
            }
        ],
    }


def build_foundry_manifest(agent: str, cfg: dict[str, Any]) -> dict[str, Any]:
    rubric = cfg["custom_rubric_evaluators"][0]
    return {
        "schema": "threadlight-foundry-package/v1",
        "generated_by": MARKER,
        "agent": {
            "kind": "foundry-hosted",
            "agent_name": agent,
            "agent_id": None,
            "agent_version": None,
            "fallback_active": False,
        },
        "telemetry": {"app_insights_connection_id": None, "trace_id": None},
        "evaluation": {
            "eval_run_id": None,
            "builtin_evaluators": [e["evaluator_name"] for e in cfg["builtin_evaluators"]],
            "custom_rubric_evaluators": [
                {
                    "name": rubric["name"],
                    "anchors": rubric["anchors"],
                    "derived_from_acceptance_criteria": rubric["derived_from_acceptance_criteria"],
                    "threshold": rubric["threshold"],
                    "score": None,
                }
            ],
            "target": dict(cfg["target"]),
        },
    }


# --------------------------------------------------------------------------- main

def generate(project_dir: Path, force: bool) -> list[str]:
    spec_path = project_dir / "specs" / "SPEC.md"
    manifest_path = project_dir / "specs" / "manifest.json"
    if not spec_path.is_file() or not manifest_path.is_file():
        raise WorkspaceError("workspace needs specs/SPEC.md and specs/manifest.json")
    spec = spec_path.read_text(encoding="utf-8")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    kind = agent_type(spec)
    if kind == "prompt":
        raise PromptAgentRefused(
            "SPEC section 11e sets agent_type: prompt. generate_only uses the GHCP pilot scaffold, "
            "which produces a Foundry HOSTED agent only. Set agent_type: hosted, or create the "
            "trivial prompt agent with the threadlight-deploy prompt-agent path (needs a subscription)."
        )
    if kind != "hosted":
        raise WorkspaceError(f"SPEC section 11e agent_type must be hosted or prompt, got {kind!r}")

    agent = _slug(str(manifest.get("name") or project_dir.name))
    project = agent
    description = str(manifest.get("description") or "").strip().replace("\n", " ")
    plan = tools(spec)
    scen = design_dataset(project_dir) or scenarios(spec)
    rules = business_rules(spec)
    skills_dir = project_dir / "src" / "agent" / "skills"
    skills = sorted(p.parent.name for p in skills_dir.glob("*/SKILL.md")) if skills_dir.is_dir() else []

    pyproject = (GHCP / "pyproject.toml").read_text(encoding="utf-8").replace(
        'name = "my-agent"', f'name = "{agent}"'
    )
    instructions_src = project_dir / "AGENTS.md"
    instructions = (
        instructions_src.read_text(encoding="utf-8")
        if instructions_src.is_file()
        else f"# {agent}\n\nFollow specs/SPEC.md. Cite the business rule that fired in every decision.\n"
    )
    cfg = build_eval_config(agent, rules, scen)
    dataset = "".join(
        json.dumps({k: s[k] for k in ("id", "query", "expected", "business_rules", "category")}) + "\n"
        for s in scen
    )
    postdeploy = {
        "schema": "threadlight-postdeploy-manifest/v1",
        "phase": "pending-deploy",
        "generate_only": True,
        "agent_name": agent,
        "agent_kind": "foundry-hosted",
        "deployment_manifest": manifest.get("deployment_manifest") or {},
        "expected_tools": [t["name"] for t in plan],
        "scenarios": [s["id"] for s in scen],
        "gaps": [
            "not deployed: generate_only run without a subscription",
            "no agent invocation, App Insights trace or Foundry eval run recorded",
            "deferred: T-0, Phase 3.5, Phase 6.5 Azure steps, Phase 7 Citadel (see specs/deferred-steps.md)",
        ],
    }

    text_outputs: dict[str, str] = {
        "azure.yaml": render_azure_yaml(project, agent, description),
        ".dockerignore": (PILOT / "dockerignore").read_text(encoding="utf-8"),
        "hooks/postdeploy.sh": (PILOT / "hooks" / "postdeploy.sh").read_text(encoding="utf-8"),
        "infra/main.parameters.json": (PILOT / "infra" / "main.parameters.json").read_text(encoding="utf-8"),
        "src/agent/container.py": (GHCP / "container.py").read_text(encoding="utf-8"),
        "src/agent/Dockerfile": (GHCP / "Dockerfile").read_text(encoding="utf-8"),
        "src/agent/.dockerignore": (GHCP / "dockerignore").read_text(encoding="utf-8"),
        "src/agent/pyproject.toml": pyproject,
        "src/agent/requirements.lock": (GHCP / "requirements.lock").read_text(encoding="utf-8"),
        "src/agent/copilot-instructions.md": instructions,
        "src/agent/tests/test_agent_package.py": render_agent_tests(plan, skills),
        "src/mcp/server.py": render_mcp_server(project, plan),
        "src/mcp/Dockerfile": (PILOT / "mcp" / "Dockerfile").read_text(encoding="utf-8"),
        "src/mcp/requirements.lock": (PILOT / "mcp" / "requirements.lock").read_text(encoding="utf-8"),
        "evals/eval_dataset.jsonl": dataset,
        "evals/eval-config.json": json.dumps(cfg, indent=2) + "\n",
        "evals/run_evals.py": (GEN / "templates" / "run_evals.py.tmpl").read_text(encoding="utf-8"),
        "evals/requirements.lock": (GEN / "locks" / "evals.requirements.lock").read_text(encoding="utf-8"),
        "specs/deployment-posture.md": render_posture(project),
        "specs/deferred-steps.md": render_deferred(project),
        "specs/project-tools.json": json.dumps({"generated_by": MARKER, "tools": plan}, indent=2) + "\n",
        "specs/foundry-package-manifest.json": json.dumps(build_foundry_manifest(agent, cfg), indent=2) + "\n",
        "tests/postdeploy-manifest.json": json.dumps(postdeploy, indent=2) + "\n",
        "DEPLOY.md": render_deploy_md(project, agent, plan),
    }
    hooks_text = text_outputs["hooks/postdeploy.sh"]
    text_outputs["hooks/postdeploy.sh"] = hooks_text.replace("__AGENT_NAME__", agent)
    binary_outputs = {"infra/main.bicep": (PILOT / "infra" / "main.bicep").read_bytes()}

    existing = sorted(p for p in [*text_outputs, *binary_outputs] if (project_dir / p).exists())
    if existing and not force:
        raise OverwriteRefused(existing)
    for stale in ("agent.yaml", "src/agent/agent.yaml"):
        if (project_dir / stale).exists():
            raise WorkspaceError(
                f"{stale} exists; generate-only defines the hosted agent inline in azure.yaml. "
                "Remove it (it came from `azd ai agent init`) and re-run."
            )
    if (project_dir / "infra" / "core").exists():
        raise WorkspaceError("infra/core exists (azd ai agent init layout); remove it, the pilot uses infra/main.bicep")

    for rel, content in text_outputs.items():
        dest = project_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8", newline="\n")
    for rel, content in binary_outputs.items():
        dest = project_dir / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(content)
    (project_dir / "hooks" / "postdeploy.sh").chmod(0o755)
    (project_dir / "evals" / "run_evals.py").chmod(0o755)
    return sorted([*text_outputs, *binary_outputs])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--project", required=True, type=Path, help="design workspace to complete in place")
    parser.add_argument("--force", action="store_true", help="overwrite previously generated files")
    args = parser.parse_args(argv)
    try:
        written = generate(args.project.resolve(), args.force)
    except PromptAgentRefused as exc:
        print(f"generate_only: refused: {exc}", file=sys.stderr)
        return 4
    except OverwriteRefused as exc:
        print(
            "generate_only: refusing to overwrite generated files (re-run with --force): "
            + ", ".join(exc.files),
            file=sys.stderr,
        )
        return 5
    except (WorkspaceError, ValueError, OSError) as exc:
        print(f"generate_only: {exc}", file=sys.stderr)
        return 2
    print(json.dumps({"status": "generated", "project": str(args.project), "files": written}, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
